### PR TITLE
Add a format attribute

### PR DESCRIPTION
**Pull request by LebedevRI**
(cherry picked from commit darktable-org/darktable@53419576791f717eb16aab22265254be74a05133)

### CODE REVIEW

**Comment by klauspost** [comment]
What does `__attribute__ ((format (printf, 1, 2)));` indicate/do?

**Comment by LebedevRI** [comment]
It allows a compiler to check arguments against a format string: https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-g_t_0040code_007bformat_007d-function-attribute-3085

I.e. if you format string is "%s" and there is no arguments, or argument is not a string, it would catch that.
It allowed me to catch those 4 other changes that are not +"**attribute** ..."

Do not know if it works with msvc too(if not, i hope it's just a NOP there..), but it does work with gcc and clang.

**Comment by klauspost** [comment]
If the compiler isn't GCC, there should be a define:

``` C
#define __attribute__(A) /* do nothing */
```

**Comment by LebedevRI** [comment]
I do not have a non-linux machine so i can not check that it builds with non-GCC.
Does your last commit mean that i should add that to a PR? If yes, then where would you suggest i should put it (remember: i can _not_ check on win)

**Comment by klauspost** [comment]
@LebedevRI - yes - please make a #define that disables this pragma on everything but GCC.

**Comment by LebedevRI** [comment]
@klauspost ee354c0fca6fc8aaa32a65dd7632a25c5d0398b9
I'm sorry, i have not even checked whether that builds, i do not know if that works and is that sufficient.

**Comment by LebedevRI** [comment]
Rebased. (i'm sorry, i still do not know if the way i disabled **attribute** works/sufficient).

**Comment by klauspost** [comment]
I will give it a shot! Thanks!

**Pull request merged**
