### PR TITLE
Add basic decoding of ARRI ALEXA (ARRI-RAW) files.

### PR DESCRIPTION
**Pull request by klauspost**

### CODE REVIEW

**Comment by klauspost** [comment]
ok, this is pretty much as far as I can get. 

Any objections to merging this?

I have placed a test file here: http://files.klauspost.com/arri/

No - I don't have a matrix, and black/whitepoint should probably be adjusted.

**Comment by pedrocr** [comment]
At a quick glance looks fine to me. Do you have any particular interest in this camera or is it just for fun?

**Comment by klauspost** [comment]
No, only that it is a camera being used. I was able to almost implement it with the naked decoder, but every second pixel was swapped, so I just thought why not just fix that :)

**Comment by klauspost** [comment]
WB and ISO fields are pure guesses though.

**Pull request merged**
