### PR TITLE
Sync in changes from darktable. Fixes #158. Fixes #161. Fixes #162.

### LINKED ISSUE #158: Nikon, compressed raws: an issue with whitelevel
@klauspost 
Hi.

I have noticed a strange thing.

Sample raw file is attached to https://redmine.darktable.org/issues/11135

When converting it to dng, the metadata says Whitelevel=3880.
If i load it via rawspeed, the used whitelevel is 3880.

But if i load the original raw file, rawspeed tells me it's whitelevel is 4095.
(Despite the fact that in cameras.xml i set whitelevel to 3880.)

And the histograms/brightness(?) for these 2 versions of the same image do not match.

Offending lines:
https://github.com/klauspost/rawspeed/blob/00f70efab95856d0421ca37b6c708be8cf55ec54/RawSpeed/NikonDecompressor.cpp#L94-L95

If i manually set whitelevel for that nef to 3880, or delete these 2 lines, the histograms and brightness(?) do match.
(not counting slight differences in crop)

Which one is wrong? The dng metadata or those overrides?

### PR DESCRIPTION
**Pull request by LebedevRI**
All right, i guess it is time for a sync again.

Gist:
- Shitload of **Nikon** white-level fixes.
- Fixes for building with with **libjpeg** (as opposed to **libjpeg-turbo**)
- **XSD** for `cameras.xml`. Will allow us in darktable to do some better checks during CI. Would have prevented `Remove stray ">" in PENTAX K-70 ID.`
- `nikon_override_auto_black` hint is no more needed, and was removed.
- **Heap-allocate** big things that were stack-allocated before. Was part of cleanup to support running darktable on `musl libc`.
- Some more camera support, highlights:
  - **Canon EOS 5D Mark IV**, only full raw, i did not get m/s RAW samples yet. 
  - **Canon EOS 80D m/s RAW** support, same as https://github.com/klauspost/rawspeed/pull/161 
- A few white level fixes for Canon :(
- A bit of **undefined behavior** fixes
- Add missing `Throw` in `RawDecoder::setMetaData()` if no `cam`. Prevents loading of broken images when guessing (`failOnUnknown`) is disabled.

Now what this does not fix:
These 3 cameras got disabled:
```
Camera ["NIKON CORPORATION", "NIKON D3X", "12bit-compressed"] has too high white level: 4096 (>= ((2^12)-1), which is 4095)
Camera ["NIKON CORPORATION", "NIKON D3X", "12bit-uncompressed"] has too high white level: 4096 (>= ((2^12)-1), which is 4095)
Camera ["NIKON", "E8400", "12bit-compressed"] has too high white level: 4095 (>= ((2^12)-1), which is 4095)
Camera ["NIKON", "E8400", "12bit-uncompressed"] has too high white level: 4095 (>= ((2^12)-1), which is 4095)
Camera ["NIKON", "E8800", "12bit-compressed"] has too high white level: 4095 (>= ((2^12)-1), which is 4095)
Camera ["NIKON", "E8800", "12bit-uncompressed"] has too high white level: 4095 (>= ((2^12)-1), which is 4095)
```
They can be trivially re-enabled after a raw sample for each is found, to check white levels.
Not sure, should i enable them in this pr, for upstreaming? May complicate upstreaming later on.

And, it was found that `NIKON D5100` is lying (duh), in this case it marks compressed raws as uncompressed, https://redmine.darktable.org/issues/11268, or at least it seems so.

Special thanks to @schenlap.

### CODE REVIEW

**Review by axxel — COMMENTED** [review]
Shouldn't those "don't load uint32 from misaligned addresses" patches rather be handled along the lines of https://github.com/klauspost/rawspeed/commit/8e0ad84d91bce504a22ef6933de885f687bcf7c4 ? Thereby avoiding the memcpy in a hot path. I have not benchmarked it but I'd expect it to be performance relevant.

**Comment by LebedevRI** [comment]
@klauspost friendly ping :)

**Comment by LebedevRI** [comment]
And some more fixes:
- Fix for name mangling when reading **DNG**'s from **nikon**. Now that nikon cameras in `cameras.xml` have only entries with `mode="???"`, it did not work, thus breaking **name demangling**.
- Proper(?, at least better) order for black levels in Rw2 raws. It seems to be in CFA order, and the original code did not work for LX15 highest ISO - the sep black levels were in different order compared to DNG.

**Comment by LebedevRI** [comment]
@axxel i guess now you know how to contribute :)
I have simply fixed it the way it did fix it. I did not benchmark and did not know about https://github.com/klauspost/rawspeed/commit/8e0ad84d91bce504a22ef6933de885f687bcf7c4

Benchmark it, and based on the results, possibly change code and PR it.
As you can see, upstreaming changes into rawspeed is .. time-y process, so you may want to PR to https://github.com/darktable-org/darktable :)

**Comment by LebedevRI** [comment]
@klauspost thank you!

**Pull request merged**
