### PR TITLE
Added camera definition for legacy Canon EOS 300D / DIGITL REBEL

### PR DESCRIPTION
**Pull request by fedxa**
Values borrowed from darktable, alias added to match old files I have in my archive.

### CODE REVIEW

**Comment by klauspost** [comment]
Merged manually to avoid duplicate.

**Comment by pedrocr** [comment]
@fedxa where did you get the DIGITAL REBEL alias? Do you have an example file where the camera identifies like that?

**Comment by fedxa** [comment]
@pedrocr Yes, I have an ancient CRW file.  If you want to look at it:
https://dl.dropboxusercontent.com/u/41790402/CRW_8206.CRW
I do not have the camera though.

NB. Of course, this is rather an antique for the current world.

**Comment by pedrocr** [comment]
@fedxa I need the actual CRW raw file to check for support. Could you please provide a sample? A dropbox or similar link would be fine. These Canon cameras with different names in the raw file are a pain in the ass.

**Comment by fedxa** [comment]
@pedrocr Uups, sorry -- pasted wrong link and did not notice! The correct one is https://dl.dropboxusercontent.com/u/41790402/CRW_8206.CRW

**Comment by pedrocr** [comment]
Awesome, thanks. Here's the darktable commit to add support for these files:

https://github.com/darktable-org/darktable/commit/826152bc3564e74133680cc53e69e040d3663b47

If you could provide this file to rawsamples.ch it would be great.

**Comment by fedxa** [comment]
Emailed the file to them.

**Pull request closed without merging**
