### PR TITLE
Fix broken compile

### PR DESCRIPTION
**Pull request by pedrocr**
I've needed to make this change to make the new metadata stuff compile. These last few updates also make darktable crash in weird ways. I'd guess something is trampling on memory somewhere.

### CODE REVIEW

**Comment by klauspost** [comment]
Ah - yeah - forgot that GCC doesn't like class prefixes in definitions.

**Comment by pedrocr** [comment]
Btw, I've had to back out these changes. They cause darktable to crash semi-randomly. Not sure what it could be yet.

**Comment by klauspost** [comment]
I should have fixed the crash now.

**Comment by pedrocr** [comment]
The crash was the missing initialization you just merged. The extra hint can probably be removed, it turned out not to be needed.

**Pull request merged**
