### PR TITLE
sNEF, new take.

### PR DESCRIPTION
**Pull request by klauspost**
Continuation of #56

This PR does conversion similar to dcraw, except we output 16 bits instead of rounding to 12 bits, and we do dithering. 

White should be 65535.

### CODE REVIEW

**Comment by pedrocr** [comment]
You can see the output here:

http://scratch.corujas.net/sNEFtests/

Something is clearly wrong with this new code as is very evident. The cameras.xml definition I'm using is this:

``` xml
    <Camera make="NIKON CORPORATION" model="NIKON D810" mode="sNEF-uncompressed">
        <Crop x="0" y="0" width="0" height="0"/>
        <Sensor black="0" white="65535"/>
        <Hints>
            <Hint name="nikon_override_auto_black" value=""/>
        </Hints>
    </Camera>
```

The current code is also wrong as there are some strange artifacts in some areas and the background looks darker.  The matrix reversal that you were going to do in #72 may be needed. Alternatively we could go back to leaving the colors/WB intact and signal that to the calling program.

**Comment by klauspost** [comment]
Both artifact issues should now be fixed - overflows & wrong blue color every second pixel. AFAICT the hint shouldn't be needed.

**Comment by klauspost** [comment]
This code has a lot less "magic", and the algorithm probably originates from Adobe, who has access to more information than we do.

**Comment by pedrocr** [comment]
I've updated the images and used a simpler cameras.xml section:

``` xml
    <Camera make="NIKON CORPORATION" model="NIKON D810" mode="sNEF-uncompressed">
        <Crop x="0" y="0" width="0" height="0"/>
        <Sensor black="0" white="65535"/>
    </Camera>
```

The artifacts in the current branch are gone and the image seems almost correct. It only seems to be about overexposed. If I reduce the exposure by 2 stops I get an image that looks correct in terms of color and curve but with some clipped highlights.

**Comment by klauspost** [comment]
2 stops is kind of an odd number. I would expect it to be either correct, or off by 4 stops.

If you take out

``` Cpp
  // Scale output values to 16 bits.
  for (int i = 0 ; i < 4096; i++) {
    int c = curve[i];
    curve[i] = clampbits(c<<4, 16);
  }
```

The output values should  be in a similar range to dcraw. Since it reported white to be at 4095, it seemed sensible to scale that by the remaining 4 bits.

Can you see what the correct white value would be if you take out the scaling?

**Comment by pedrocr** [comment]
Without the scaling a 16384 white point looks perfect as does 65535 with a shift of 2 instead of 4. Before scaling curve[4095] is 65535 which is odd.

**Comment by klauspost** [comment]
Weird. I can't find anything that would contribute to the last 2 bits. However, let's go with shift 2, so we do the upscaling (and dithering) in one pass.  I will adjust it when I get home and merge.

**Comment by klauspost** [comment]
(it could also well be that dcraw just reported a wrong value)

**Pull request merged**
